# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: mirrorz.org

exclude: [tunasync, _tuna, README.md, sjtug, tuna, sjtug]

# vim: ts=2 sts=2 sw=2 expandtab
